application: new-project-template
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /_ah/warmup
  login: admin
  script: main.application

- url: .*
  script: main.application

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?doctests\.py[co]?
- ^(.*/)?unittests\.py[co]?
- ^(.*/)?.*tests\.py[co]?
- ^(.*/)?LICENSE\.txt
- ^(.*/)?.*\.orig
- ^(.*/)?.*\.swp
- ^(.*/)?.*\.dummy

builtins:
- remote_api: on
- appstats: on
#- deferred: on

inbound_services:
- warmup

#admin_console:
#  pages:
#  - name: Custom Page
#    url: /admin/

#error_handlers:
#  - file: default_error.html
#
#  - error_code: over_quota
#    file: over_quota.html
#
#  - error_code: timeout
#    file: timeout.html

libraries:
#- name: django
#  version: latest
#- name: PIL
#  version: latest
